### ISSUE TITLE
seanimations moving entire model when not supposed to bug

### ISSUE THREAD

**Issue by Gal4xycod** [SE2Dev/io_anim_seanim#12]
When importing an .seanim file onto a Cod Xmodel, the animation has movement that is not supposed to be apart of the animation. For example. Casual_stand_idle for a Soldier is supposed to be the soldier standing idle and NOT MOVING. However the idle animation plays but the entire model moves with the animation and basically shifting around all over the place. Another example is a running animation. Combatrun_Forward_1 is supposed to have the model moving straight without moving up or down....just a straight path forward. When i viewed the animation in blender the model would move up near the end of the animation and then loop back down to the ground. Again not supposed to happen and unfortunately the animation was like that when i got it in Source. But yeah im porting cod models to source, I can't really port these animations due to how broken seanim imports the animations. The animations are not entirely broken, it just has movement thats not supposed to be apart of the animation. I viewed the animations in Maya and that weird movement that i see in blender does not happen in Maya. Hopefully this can be resolved soon. 

Here are some clips ( and blender image ) i recorded in-game of this animation problem im talking about. The animations also do this in Blender.

![crouchingmovementbug](https://user-images.githubusercontent.com/49221361/55452833-57a76b80-55a7-11e9-8ad4-1aa3a552719a.PNG)
Notice how the model is under the grid. This means when the animation plays in-game, the model will be underground as the grid in blender represents the ground or flat surface in-game. I can't fix this issue either.

Video 1: https://youtu.be/on6MWNj4C-4
Video 2: https://youtu.be/iLcGoIRbaB4

Animation's used in the clips as examples. By the way, this issue happens with almost all seanim's i tried
Untextured Roebuck World at war: combatrun_forward_1
Unfinished Modern Warfare marine: precombatrun1

**Comment by SE2Dev** [comment]
This issue is caused by a combination of Blender-CoD being outdated, and the legacy scale constant (which was originally present to ensure compatibility with Blender-CoD), which was removed in io_seanim v0.3.8.

Originally all animations were scaled by down by 2.54 because Wraith internally converted the units to cm whereas Blender-CoD uses inches; this feature was removed in io_seanim v0.3.8 to ensure proper compatibility with other games, but Blender-CoD hasn't been updated yet.

The current solution is to set the model scale to 2.54 when import XMODEL_EXPORT files in Blender-CoD (as seen below).

![image](https://user-images.githubusercontent.com/5873790/56519486-2d92fa80-6510-11e9-9074-4a72a010c807.png)
